version: '3.9'

services:
  db:
    image: postgres:15.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod

  web:
    restart: always
    build: ./
    volumes:
      - ./:/social_network
    ports:
      - '8000:8000'
    command: >
      sh -c 'python manage.py makemigrations && 
      python manage.py migrate &&
      gunicorn social_project.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod

volumes:
  postgres_data: