# Generated by Django 4.1.6 on 2023-03-05 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reciever_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='message',
            name='user_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sender_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
    ]
