# Generated by Django 4.1.6 on 2023-02-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение пользователя', 'verbose_name_plural': 'Сообщении пользователей'},
        ),
    ]
