# Generated by Django 4.1.6 on 2023-02-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0003_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hide',
            field=models.JSONField(default={}),
        ),
    ]
