# Generated by Django 4.1.6 on 2023-02-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0007_alter_message_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='hide',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
