# Generated by Django 4.1.6 on 2023-02-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0010_message_room_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room_message',
        ),
    ]
