# Generated by Django 4.1.6 on 2023-02-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teampost',
            options={'verbose_name': 'Пост команды', 'verbose_name_plural': 'Посты команд'},
        ),
    ]
