# Generated by Django 4.1.6 on 2023-02-16 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_app', '0002_alter_teampost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='all_subscribers_post', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики команды'),
        ),
    ]
