# Generated by Django 4.1.6 on 2023-02-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0007_remove_team_subscribers_subscribersteam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribersteam',
            options={'verbose_name': 'Подписчика команды', 'verbose_name_plural': 'Подписчики команды'},
        ),
    ]
