# Generated by Django 4.1.6 on 2023-02-15 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team_app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_team_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_team_post', to='team_app.teampost', verbose_name='Комментарии к посту в команде'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_user_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_user_post', to='profile_app.userpost', verbose_name='Комментарии к посту пользователя'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
