# Generated by Django 4.1.6 on 2023-02-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
    ]
