# Generated by Django 4.1.6 on 2023-02-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_alter_user_phone_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментарий пользователя', 'verbose_name_plural': 'Комментарии пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userpost',
            options={'verbose_name': 'Пост пользователя', 'verbose_name_plural': 'Посты пользователей'},
        ),
    ]
