# Generated by Django 4.1.6 on 2023-03-01 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0009_subscribe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='followers',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='subscribe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscribe', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
