# Generated by Django 4.1.6 on 2023-03-01 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0010_remove_subscribe_follow_remove_subscribe_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='subscribe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_in_user', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subs', to=settings.AUTH_USER_MODEL),
        ),
    ]
