# Generated by Django 4.1.6 on 2023-03-01 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0011_alter_subscribe_subscribe_alter_subscribe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='publish_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
