# Generated by Django 4.1.6 on 2023-03-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0012_userpost_publish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_fields',
            field=models.JSONField(default=list),
        ),
    ]
