# Generated by Django 4.1.6 on 2023-03-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0013_user_hide_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hide_fields',
            field=models.JSONField(default=dict),
        ),
    ]
