# Generated by Django 4.1.6 on 2023-03-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0014_alter_user_hide_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hide_fields',
        ),
    ]
